[package]
name = "x16rs-sys"
description = "x16rs c binding for rust"
license = "MIT"
repository = "https://github.com/hacash/x16rs-sys" 
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
hex = "0.4.3"
